apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: pelfegor/user-service:1.2.0

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: user-service-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20